### PR TITLE
PHP8 Support

### PR DESCRIPTION
**Pull request by tertek**
Fix non-static method error.

### CODE REVIEW

**Comment by tertek** [comment]
I had to also change the log method because it threw an error in some cases which I could not resolve.

**Comment by tertek** [comment]
@lsgs Do you think you can look into this in the near time, since we are planning to upgrade to PHP8. THanks

**Review by lsgs — APPROVED** [review]

**Comment by lsgs** [comment]
That's great @tertek. Thank you! I have another couple of fixes to make but will get this out as soon as I can.

**Comment by tertek** [comment]
@lsgs Perfect. Thank you too!

**Pull request merged**
